src/hash/hash.test.ts
src/hash/hash.ts
src/index.ts
src/verify.integration.test.ts
src/verify.test.ts

Returns an array of promises, each promise corresponds to a verification check.
The last promise resolves to the overall validity based on all the checks.
This allows us to work on the promises independently from the other verification checks.

feat: add verifyWithIndividualChecks

---

.eslintrc.json
README.md
package.json
src/index.ts
src/verifiers/openAttestationDnsTxt.ts
src/verifiers/openAttestationDnsTxt.v2.test.ts
src/verifiers/openAttestationDnsTxt.v3.test.ts
src/verify.v2.integration.test.ts

- only verify if the issuer is using DNS-TXT (dont throw error if he's not)
- added resolution status for every issuer, even if it has been skipped for one person
- forward the resolution status in the data object

fix: dns verifier

---

src/types/error.ts
src/verifiers/issuerIdentity/didIdentityProof/didIdentityProof.test.ts
src/verifiers/issuerIdentity/didIdentityProof/didIdentityProof.ts

- disallowing "SKIPPED" status on `didIdentityProof` & letting it fail on mixture of `identityProof.type`
- refactored error handling to use `withCodedErrorHandler`

feat: stricter did identity

---

src/types/error.ts
src/verifiers/issuerIdentity/dnsDidProof/dnsDidProof.test.ts
src/verifiers/issuerIdentity/dnsDidProof/dnsDidProof.ts

- refactored to use `withCodedErrorHandler`
- changing `SKIPPED` to `INVALID` on mixture of `identityProof.type`

feat: stricter dns did identity

---

.gitignore
package-lock.json
package.json
src/getIdentifier.test.ts
src/getIdentifier.ts
src/index.ts
src/verifiers/issuerIdentity/did/didIdentityProof.ts
src/verifiers/issuerIdentity/dnsDid/dnsDidProof.ts

context: https://www.pivotaltracker.com/story/show/176797200
this pr does the following:
- adds `getIdentifier` and `getIdentityFragment` utils
- adds istanbul coverage folder to .gitignore

feat: add getIdentifier and getIdentityFragment util

---

package-lock.json
package.json

there is an interface change in ethr-did-resolver 3.0.3 to 3.1.0, which causes resolving a public key to break.
this fix pins the dependency to 3.0.3.

fix: pin ethr-did-resolver to 3.0.3

---

README.md
src/common/utils.test.ts
src/common/utils.ts
src/config.ts
src/did/resolver.test.ts
src/did/resolver.ts
src/index.ts
src/types/core.ts
src/verifiers/verificationBuilder.ts
src/verify.v2.integration.errors.test.ts
src/verify.v2.integration.test.ts
src/verify.v3.integration.test.ts

- Added a common way to use provider

feat: add standardised common Provider

---

package-lock.json
package.json
src/verifiers/documentStatus/utils.ts

Update document-store package so as to fix the import path for `DocumentStore`. Related to https://github.com/Open-Attestation/document-store/pull/99.
* Bump document-store version
* Update `DocumentStore` import path

fix: import path from document store

---

src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.test.ts
src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.ts
src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.type.ts
src/verifiers/documentStatus/utils.ts
test/fixtures/v2/did-revocation-ocsp-signed.json

- The original verification behaviour against an OCSP Responder started off with revocation by document ID
- In order to align with how we perform revocation of documents issued onto the Ethereum document store, revocation by merkle root and intermediate hashes should be performed by the OCSP Responder (i.e. do not revoke by document id)
- Related PR: Open-Attestation/ocsp-responder/pull/1

feat: ocsp revocation against merkle root & intermediate hashes

---

src/common/utils.ts

As [suggested](https://docs.tradetrust.io/docs/appendix/tradetrust-api/#verify-endpoint), I was trying to setup my own version of the oa-verify api. I'm trying to target the Goerli test network, since Ropsten and Rinkeby will become deprecated in the future. (See [this](https://ethereum-magicians.org/t/og-council-post-merge-testnets/9034) for more info). 
I did come across the same issue as @HJunyuan described [here](https://github.com/Open-Attestation/oa-verify/issues/223). I looked at the logic of the code and I think just removing the warning message will fix the false positive. Feel free to correct/comment if removing this line has any other side effects for the package! 😄 
Fixes #223

fix: false positive for warnProvider message

---

src/verifiers/verificationBuilder.ts

Related to this [PR](https://github.com/Open-Attestation/oa-verify/pull/232) and [issue](https://github.com/Open-Attestation/oa-verify/issues/223), was still receiving the `warnProvider` message, even though I configured a full custom provider.
I played around with the package and I think this small logic change will also fix this false positive warning for the verificationBuilder. It will still give the warning if you are using the default provider, but not when you configured your own provider or resolver now! 😄

fix: false positive warning in verificationBuilder

---

package-lock.json
package.json

Bump version for dnsprove.
* Update dnsprove package to `^2.5.0`
* https://github.com/Open-Attestation/dnsprove/pull/28
* https://github.com/Open-Attestation/dnsprove/pull/29
* https://www.pivotaltracker.com/story/show/183221914
* https://www.pivotaltracker.com/story/show/183222257

feat: bump dnsprove version

---

src/index.ts

What is the background of this pull request?
This pr exposes the `verifySignature` function.
This convenience function would be used for verification of did:eth documents without the use the hefty structure of a verifier.

fix: expose verify signature

---

package-lock.json
package.json

Fixes an issue with commonjs digesting the lib due to the new document store package.
* This PR should also improve the overall package size by about 85% from 2.53mb to 366.1kb.
* Exposes commonjs, esm and umd versions to fit more projects using it
- Change module build setup by replacing tsc with a bundler

fix: module build

---

package.json

End-users are not able to import the `oa-verify` library successfully:
- `type: "commonjs"` was conflicting with instruction to export as module causing end-users will face this error:
```text
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module'
```
- Typo on `exports.default` path 
- Remove `type` and `source`
- Fix `exports.default` file path (was missing `m` previously)
- Add `exports.import` and `exports.types` file path
```jsonc
{
// ...
"exports": {
"require": "./dist/index.js",
"import": "./dist/index.modern.mjs",
"default": "./dist/index.modern.mjs",
"types": "./dist/types/index.d.ts"
},
// ...
}
```

fix: exports path

---

.github/workflows/tests.yml

GitHub Actions workflow (`.github/workflows/tests.yml`) keeps failing when running `npm run test:ci`. Probably due to not specifying an Infura API key or the default one is being overused?
Set a `PROVIDER_API_KEY` env var specifically when running `npm run test:ci`

ci: set PROVIDER_API_KEY from GitHub repository variable

---

package-lock.json
package.json
src/common/utils.ts
src/types/core.ts
src/verifiers/issuerIdentity/dnsDid/dnsDidProof.ts
src/verifiers/issuerIdentity/dnsTxt/openAttestationDnsTxt.ts
src/verifiers/verificationBuilder.ts

This PR allows users to specify custom DNS resolvers in the verification builder.
Note: This merges with `master` branch
- Add a `dnsResolvers` option to the verification builder
- `Gitlab issue link` (I can't access it, will add it after I can access it again)

feat: dns resolver option

---

jest.config.js
package-lock.json
package.json

Update the document store package to use the bundled version.
- Update document store to v4.1.0
- https://sgts.gitlab-dedicated.com/wog/gvt/gds-ace/general/dlt/galaxies-stories/trustdocs-stories/-/issues/313

fix: update doc store

---

package-lock.json
package.json

The ESM build of `ethr-did-resolver` seems to be mixing cjs, which will fail in esm only environments. Something like that https://github.com/decentralized-identity/ethr-did-resolver/issues/186.
Ideally `ethr-did-resolver` should be rebuilt to only contain ESM code, but since we have no control over that and I do not want to fork them, we can inline the code directly during bundling, this is done by shifting `ethr-did-resolver` to dev deps (a microbundler behaviour).

fix: force microbundler to inline and transpile ethr-did-resolver

---

src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.test.ts
src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.type.ts
src/verifiers/documentStatus/revocation.types.ts

To support the [new reason code](https://github.com/Open-Attestation/ocsp-responder/pull/21) `1001` which represents the `suspended` document status on [OCSP responder](https://github.com/Open-Attestation/ocsp-responder)
- update `ValidOcspReasonCode` to validate reason code `1001`
- update `OcspResponderRevocationReason` to return `SUSPENDED` for reason code `1001`
- Add test cases for these updates

feat: add support for ocsp reason code suspended
